language: node_js
node_js: "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script: npm run ci
after_success:
  - yarn run test:coverage
